version: '2'
services:
    hipster-postgresql:
        image: postgres:9.6.5
        volumes:
            - ~/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=hipster
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
